repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3          # sempre atualiza aqui: https://github.com/astral-sh/ruff-pre-commit
    hooks:
      - id: ruff
      - id: ruff-format   # esse aqui jรก substitui o black
