[package]
name = "capturer"
version = "0.1.0"
edition = "2024"

[dependencies]
pcap = "2.4.0"
reqwest = { version = "0.12.24", features = ["blocking", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

